apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: spring-petclinic-config
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dperez-unir/spring-petclinic-microservices-config
  ref:
    branch: main
  secretRef:
    name: flux-git-auth