apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: petclinic-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: spring-petclinic-config
  update:
    path: ./k8s/
    strategy: Setters
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: david.perez945@comunidadunir.net
        name: david-unir
      messageTemplate: "ci: update images"
    push:
      branch: main
