apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
      annotations:
        fluxcd.io/automated: "true"
        fluxcd.io/image-ref.visits-service: "visits-service-policy"
    spec:
      containers:
        - name: visits-service
          image: davidunir945/spring-petclinic-visits-test:3.2.38
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: visits-service
