apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: admin-server-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: admin-server-images
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api-gateway-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: api-gateway-images
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: config-server-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: config-server-images
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: customers-service-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: customers-service-images
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: discovery-server-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: discovery-server-images
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vets-service-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vets-service-images
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: visits-service-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: visits-service-images
  policy:
    semver:
      range: ">=0.0.0"